-- MySQL Script generated by MySQL Workbench
-- Sun Jan 19 16:17:54 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema laraveldb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema laraveldb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `laraveldb` DEFAULT CHARACTER SET latin1 ;
USE `laraveldb` ;

-- -----------------------------------------------------
-- Table `laraveldb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laraveldb`.`User` (
  `userId` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `age` INT NULL,
  `email` VARCHAR(100) NULL,
  PRIMARY KEY (`userId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laraveldb`.`Credential`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laraveldb`.`Credential` (
  `credId` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NULL,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `role` VARCHAR(45) NULL,
  PRIMARY KEY (`credId`),
  INDEX `fk_Credential_User_idx` (`userId` ASC),
  CONSTRAINT `fk_Credential_User`
    FOREIGN KEY (`userId`)
    REFERENCES `laraveldb`.`User` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
