-- MySQL Script generated by MySQL Workbench
-- Fri Jan 31 13:21:20 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema laraveldb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema laraveldb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `laraveldb` DEFAULT CHARACTER SET latin1 ;
USE `laraveldb` ;

-- -----------------------------------------------------
-- Table `laraveldb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laraveldb`.`user` (
  `userId` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `firstName` VARCHAR(45) NULL DEFAULT NULL,
  `lastName` VARCHAR(45) NULL DEFAULT NULL,
  `picture` VARCHAR(45) NULL,
  `age` INT(11) NULL DEFAULT NULL,
  `gender` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `hometown` VARCHAR(45) NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `phoneNumber` VARCHAR(45) NULL,
  `role` VARCHAR(45) NULL,
  `isSuspended` VARCHAR(45) NULL,
  PRIMARY KEY (`userId`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
